// apps/client/pages/search.vue
<script setup>
const router = useRouter()

const vnInputId = ref(null)

function submitInput() {
  const id = vnInputId.value

  if (id)
    router.push(`/vn/${id}`)
}
</script>

<template>
  <div class="flex h-full w-96 mx-auto mt-8 py-4 bg-gray-50 shadow-xl">
    <div class="flex h-full w-full flex-col gap-6">
      <h1 class="text-3xl text-center">
        Search VNs
      </h1>
      <div class="flex flex-col justify-center items-center gap-6">
        <input v-model="vnInputId" class="w-3/4" type="number" placeholder="Enter id">
        <button type="button" class="px-8 py-2 bg-indigo-500 hover:bg-indigo-800 rounded-lg" @click="submitInput">
          <p class="text-white">
            Search
          </p>
        </button>
      </div>
    </div>
  </div>
</template>

// apps/client/src/pages/search.tsx
import type { Component } from 'solid-js';
import { createSignal } from 'solid-js';

const Home: Component = () => {
  const [name, setName] = createSignal('');
  return (
    <>
      <div class="flex h-full justify-center m-4">
        <div class="flex flex-col gap-16">
          <div class="flex flex-row h-14 w-80 justify-center border-1 border-white rounded-md bg-white hover:shadow-xl shadow-xl hover:shadow-indigo-400 shadow-indigo-300 transition-all">
            <input
              type="text"
              placeholder="Visual Novel's name"
              class="flex h-full w-full justify-start px-4 ring-0 focus:ring-0 focus:shadow-none focus:outline-none border-none focus:border-none"
              onInput={(event) => {
                setName(event.currentTarget.value);
              }}
            />
            <button class="w-20 bg-indigo-500 rounded-tr-md rounded-br-md">
              <h1 class="text-white">
                Search
              </h1>
            </button>
          </div>
          <h1 class="text-2xl">Current Name : { name }</h1>
        </div>
      </div>
    </>
  );
};

export default Home;
